
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 24;
  public static final int MOD = 26;
  public static final int READ = 8;
  public static final int OVER = 25;
  public static final int NE = 21;
  public static final int LT = 17;
  public static final int ELSE = 4;
  public static final int PLUS = 22;
  public static final int RPAREN = 28;
  public static final int THEN = 3;
  public static final int SEMI = 31;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int LBRACKET = 29;
  public static final int LPAREN = 27;
  public static final int GT = 18;
  public static final int LE = 20;
  public static final int WRITE = 9;
  public static final int ID = 13;
  public static final int RBRACKET = 30;
  public static final int NUM = 14;
  public static final int DO = 12;
  public static final int EOF = 0;
  public static final int MINUS = 23;
  public static final int GE = 19;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 15;
  public static final int EQ = 16;
  public static final int FOR = 10;
  public static final int TO = 11;
  public static final int REPEAT = 6;
  public static final int VAR = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "FOR",
  "TO",
  "DO",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "GE",
  "LE",
  "NE",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "VAR"
  };
}

